# Default values for cenylcz-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: cenylcz/cenylcz-db
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.1"

container:
  name: cenylcz-db
  port: 3306

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

service:
  type: LoadBalancer
  port: 3306

hostPath:
  path: /private/tmp/test
