apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cenylcz-db.fullname" . }}
  labels:
    {{- include "cenylcz-db.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cenylcz-db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "cenylcz-db.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.container.name | quote }}
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "cenylcz-db.fullname" . }}-secret
                  key: mysql_root_password
          volumeMounts:
            - mountPath: /var/lib/mysql # path inside container
              name: {{ include "cenylcz-db.fullname" . }}-storage
      volumes:
        - name: {{ include "cenylcz-db.fullname" . }}-storage
          persistentVolumeClaim:
            claimName: {{ include "cenylcz-db.fullname" . }}-pvc
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
