apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "cenylcz-db.fullname" . }}-pv
  labels:
    type: local
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.hostPath.path | quote }}
    type: Directory
