apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cenylcz-db.fullname" . }}-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
