apiVersion: v1
kind: Service
metadata:
  name: {{ include "cenylcz-db.fullname" . }}
  labels:
    {{- include "cenylcz-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
  selector:
    {{- include "cenylcz-db.selectorLabels" . | nindent 4 }}
