CREATE DATABASE client;
CREATE DATABASE business;
create table `client`.`user` (
    `user_key` INT NOT NULL AUTO_INCREMENT,
    `first_name` VARCHAR(25),
    `last_name` VARCHAR(25),
    `boa` TIMESTAMP NOT NULL,
    PRIMARY KEY(`user_key`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
create table `business`.`trade` (
    `trade_key` INT NOT NULL AUTO_INCREMENT,
    `ticker`  VARCHAR(10) NOT NULL,
    `quantity` INTEGER NOT NULL,
    `open_unit_cost` DOUBLE(8, 2) NOT NULL,
    `close_unit_cost` DOUBLE(8, 2) DEFAULT NULL,
    `purchase_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `close_time` TIMESTAMP NULL,
    `gain_lost_total` DOUBLE(8, 2) DEFAULT 0.0,
    `status` ENUM('Active', 'Closed') NOT NULL,
    PRIMARY KEY(`trade_key`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
CREATE table `business`.`stock` (
    `stock_key` INT NOT NULL AUTO_INCREMENT,
    `ticker` VARCHAR(8) NOT NULL,
    `description` VARCHAR(64) NOT NULL,
    PRIMARY KEY(`stock_key`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
INSERT INTO `business`.`stock` (`stock_key`, `ticker`, `description`)
VALUES
(1, 'QCOM', 'QUALCOMM Incorporated'),
(2, 'FB', 'Facebook,inc'),
(3, 'MSFT', 'Microsoft Corporation'),
(4, 'GOOG', 'Alphabet Inc'),
(5, 'AAPL', 'Apple Inc'),
(6, 'TSLA', 'Tesla Inc'),
(7, 'RCL', 'Royal Caribbean Cruises Ltd'),
(8, 'SIX', 'Six Flags Entertainment Corporation'),
(9, 'CCL', 'Carnival Corporation & Plc'),
(10, 'LUV', 'Southwest Airlines Co'),
(11, 'JBLU', 'JetBlue Airways Corporation'),
(12, 'SAVE', 'Spirit Airlines, Inc'),
(13, 'DAL', 'Delta Air Lines, Inc'),
(14, 'UAL', 'United Airlines Holdings, Inc'),
(15, 'AAL', 'American Airlines Group Inc'),
(16, 'AXP', 'American Express Company'),
(17, 'SBNY', 'Signature Bank'),
(18, 'USB', 'U.S. Bancorp'),
(19, 'WFC', 'Wells Fargo & Company'),
(20, 'JPM', 'JPMorgan Chase & Co'),
(21, 'BAC', 'Bank of America Corporation'),
(22, 'URBN', 'Urban Outfitters, Inc'),
(23, 'ROST', 'Ross Stores, Inc'),
(24, 'M', 'Macy\'s, Inc'),
(25, 'JWN', 'Nordstrom, Inc'),
(26, 'TJX', 'The TJX Companies, Inc'),
(27, 'BJRI', 'BJ\'s Restaurants, Inc'),
(28, 'TAST', 'Carrols Restaurant Group, Inc'),
(29, 'DIN', 'Dine Brands Global, Inc'),
(30, 'RRR', 'Red Rock Resorts, Inc'),
(31, 'DNKN', 'Dunkin\' Brands Group, Inc'),
(32, 'DENN', 'Denny\'s Corporation'),
(33, 'QSR', 'Restaurant Brands International Inc'),
(34, 'SBUX', 'Starbucks Corporation'),
(35, 'YUM', 'Yum! Brands, Inc'),
(36, 'DRI', 'Darden Restaurants, Inc'),
(37, 'MCD', 'McDonald\'s Corporation'),
(38, 'RRGB', 'Red Robin Gourmet Burgers, Inc'),
(39, 'EAT', 'Brinker International, Inc'),
(40, 'RUTH', 'Ruth\'s Hospitality Group, Inc'),
(41, 'TXRH', 'Texas Roadhouse, Inc'),
(42, 'CAKE', 'The Cheesecake Factory Incorporated'),
(43, 'RHP', 'Ryman Hospitality Properties, Inc'),
(44, 'SHO', 'Sunstone Hotel Investors, Inc'),
(45, 'MGM', 'MGM Resorts International'),
(46, 'WYNN', 'Wynn Resorts, Limited'),
(47, 'MAR', 'Marriott International, Inc'),
(48, 'H', 'Hyatt Hotels Corporation'),
(49, 'LVS', 'Las Vegas Sands Corp'),
(50, 'BA', 'Boeing Co'),
(51, 'EADSY', 'Airbus Se'),
(52, 'AMC', 'AMC Entertainment Holdings, Inc'),
(53, 'V', 'Visa Inc'),
(54, 'MA', 'Mastercard Incorporated'),
(55, 'WMT', 'Walmart Inc'),
(56, 'TGT', 'Target Corporation'),
(57, 'BBY', 'Best Buy Co., Inc'),
(58, 'HD', 'The Home Depot, Inc'),
(59, 'LOW', 'Lowe\'s Companies, Inc'),
(60, 'DIS', 'The Walt Disney Company '),
(61, 'NFLX', 'Netflix, Inc'),
(62, 'IRBT', 'iRobot Corporation'),
(63, 'JNJ', 'Johnson & Johnson'),
(64, 'XOM', 'Exxon Mobil Corporation'),
(65, 'CVX', 'Chevron Corporation'),
(66, 'ET', 'Energy Transfer LP'),
(67, 'SLB', 'Schlumberger Limited'),
(68, 'AWK', 'American Water Works Company, Inc'),
(69, 'F', 'Ford Motor Company'),
(70, 'PVH', 'PVH Corp'),
(71, 'OXY', 'Occidental Petroleum Corporation'),
(72, 'VYM', 'Vanguard High Dividend Yield Index Fund ETF Shares'),
(73, 'MKC', 'McCormick & Company, Incorporated'),
(74, 'VOO', 'Vanguard S&P 500 ETF'),
(75, 'MFA', 'MFA Financial, Inc.'),
(76, 'JETS', 'U.S. Global Jets ETF'),
(77, 'BBBY', 'Bed Bath & Beyond Inc'),
(78, 'HTZ', 'Hertz Global Holdings, Inc'),
(79, 'IOO', 'iShares Global 100 ETF'),
(80, 'VTV', 'Vanguard Value Index Fund ETF Shares'),
(81, 'VNQ', 'Vanguard Real Estate Index Fund ETF Shares'),
(82, 'TSN', 'Tyson Foods, Inc.'),
(83, 'EADSY', 'Airbus SE'),
(84, 'INTC', 'Intel Corporation'),
(85, 'ACB', 'Aurora Cannabis Inc'),
(86, 'NCLH', 'Norwegian Cruise Line Holdings Ltd'),
(87, 'CI', 'Cigna Corporation'),
(88, 'NBL', 'Noble Energy Inc'),
(89, 'CME', 'CME Group Inc'),
(90, 'ICE', 'Intercontinental Exchange Inc'),
(91, 'T', 'AT&T Inc'),
(92, 'IDXX', 'IDEXX Laboratories Inc'),
(93, 'ECL', 'Ecolab Inc'),
(94, 'ZTS', 'Zoetis Inc'),
(95, 'GPN', 'Global Payments Inc'),
(96, 'CDW', 'CDW Corporation'),
(97, 'LMT', 'Lockheed Martin Corporation'),
(98, 'MSCI', 'MSCI Inc'),
(99, 'PEP', 'PepsiCo, Inc'),
(100, 'TSLA', 'Tesla, Inc');
